image: buildkite/puppeteer

stages:
  - build
  - deploy

variables:
  SERVER_ADDRESS: b9labs@23.97.239.116
  TARGET_FOLDER: /var/www/html/training/

build-code:
  stage: build
  only:
    refs:
      - master
      - development
      - schedules
  tags:
    - main-runner

  before_script:
    ## Load git.b9lab.com pubkey
    - mkdir -p ~/.ssh/
    - touch ~/.ssh/known_hosts
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    ## Import deploy privkey from variable
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_RUNNER_DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - apt-get -y install git

  script:
  - git submodule init
  - git submodule update
#  - useradd -m builder
#  - su builder -s /bin/bash
  - npm install
  - npm run build || true
  - npm run build

  artifacts:
    paths:
      - public/


deploy-staging-server:
  stage: deploy
  environment:
    name: staging
    url: https://cdocs.westeurope.cloudapp.azure.com/training/
  only:
    refs:
      - master
      - development
      - schedules

  tags:
    - main-runner

  when: manual

  dependencies:
    - build-code

  before_script:
    ## Import SSH Key from variable
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_RUNNER_DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

  script:
    - rsync -a ./* ${SERVER_ADDRESS}:${TARGET_FOLDER}
