image: buildkite/puppeteer

stages:
  - build
  - deploy

variables:
  SERVER_ADDRESS: b9labs@23.97.239.116
  TARGET_FOLDER: /var/www/html/training/

build-code:
  stage: build
  only:
    refs:
      - master
      - development
      - schedules
  tags:
    - main-runner

  before_script:
    # Output vars
    - 'echo SERVER_ADDRESS: ${SERVER_ADDRESS}'
    - 'echo TARGET_FOLDER: ${TARGET_FOLDER}'
    - 'echo CI_CONTENT_COMMIT_HASH: ${CI_CONTENT_COMMIT_HASH}'
    - 'export T1=test'
    - 'echo T1=$T1'
    - 'export T2=${CI_CONTENT_COMMIT_HASH:=test2}'
    - echo $T2

    # Load git.b9lab.com pubkey
    - mkdir -p -m 0700 ~/.ssh/
    - touch ~/.ssh/known_hosts
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    
    ## Install missing packages
    - apt-get update -y
    - apt-get -y install git

    ## Add deploy key (privkey)
    - 'which ssh-agent || ( apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_RUNNER_DEPLOY_KEY" | tr -d '\r' | ssh-add -

    # check and setup variables
    - |
      if [ -v ${CI_CONTENT_COMMIT_HASH} ]; 
      then eval "export CONTENT_CHECKOUT_PARAM=${CI_CONTENT_COMMIT_HASH}" && eval "export CONTENT_BUILD_TARGET_SUBFOLDER=${CI_CONTENT_COMMIT_HASH}"; 
      else eval "export CONTENT_CHECKOUT_PARAM=master"; 
      fi

    # checkout content
    - 'echo content checkout: $(echo $CONTENT_CHECKOUT_PARAM)'
    - 'echo subfolder: $CONTENT_BUILD_TARGET_SUBFOLDER'
    
    - git submodule init
    - git submodule update
    - git -C content/ checkout $(echo $CONTENT_CHECKOUT_PARAM)


  script:
    - npm install
    - npm run build || true # workaround, first build fails
    - npm run build

  artifacts:
    paths:
      - public/


deploy-staging-server:
  stage: deploy
  environment:
    name: staging
    url: https://cdocs.westeurope.cloudapp.azure.com/training/
  only:
    refs:
      - master
      - development
      - schedules

  tags:
    - main-runner

  #when: manual

  dependencies:
    - build-code

  before_script:
    ## Import SSH Key from variable
    - mkdir -p -m 0700 ~/.ssh/
    - touch ~/.ssh/known_hosts
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    ## Install missing packages
    - apt-get update -y
    - apt-get install rsync -y

    ## Add deploy key (privkey)
    - 'which ssh-agent || ( apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_RUNNER_DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - if [ -z ${CI_CONTENT_COMMIT_HASH} ]; then export TARGET_SUB_FOLDER=$CI_CONTENT_COMMIT_HASH else export TARGET_SUB_FOLDER=; fi

  script:
    - 'echo Target: ${SERVER_ADDRESS}:${TARGET_FOLDER}/$TARGET_SUB_FOLDER'
    - rsync -avh --stats ./public/* ${SERVER_ADDRESS}:${TARGET_FOLDER}/$(echo $TARGET_SUB_FOLDER)
