image: alpine:latest

stages:
  - trigger-deployment

variables:
  APP_PROJECT_ID: 175
  CONTENT_PROJECT_ID: 173
  CI_CONTENT_COMMIT_HASH: $CI_COMMIT_SHA
  CI_JOB_TRIGGER_TOKEN: $CI_JOB_TRIGGER_TOKEN
  CI_BUILDBOT_TOKEN: $CI_BUILDBOT_TOKEN

trigger-deployment:
  stage: trigger-deployment
  tags:
    - main-runner
  only: 
    refs:
      - merge_requests
  before_script:
    - echo "CI_MERGE_REQUEST_IID $CI_MERGE_REQUEST_IID"
    - echo "CI_MERGE_REQUEST_ID $CI_MERGE_REQUEST_ID"

  script:
    - apk add curl jq
    - 'echo COMMIT SHA: $CI_COMMIT_SHA'
    - CURL_CMD=$(echo -X POST -F "token=$CI_JOB_TRIGGER_TOKEN" -F "ref=master" -F "variables[CI_CONTENT_COMMIT_HASH]=$CI_CONTENT_COMMIT_HASH" -F "variables[CI_MERGE_REQUEST_IID]=$CI_MERGE_REQUEST_IID" https://git.b9lab.com/api/v4/projects/$APP_PROJECT_ID/trigger/pipeline)
    - 'echo curl cmd: $CURL_CMD'
    - CURL_RETURN=$(curl $CURL_CMD)
    - 'echo return: $CURL_RETURN'

    - PIPELINE_URL=$(echo $CURL_RETURN | jq ".web_url")
    - PIPELINE_ID=$(echo $CURL_RETURN | jq ".id")
    - 'echo "url: $PIPELINE_URL"'

    #add notification to MR
    - echo add pipeline notification to MR
    - MESSAGE=$(echo "Started:<a href="$PIPELINE_URL">Build Pipeline $PIPELINE_ID</a>")
    - 'curl -X POST -H "PRIVATE-TOKEN: $CI_BUILDBOT_TOKEN" -F "body=$MESSAGE" https://git.b9lab.com/api/v4/projects/$CONTENT_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes'
