courseinfo:
  id: CORDA-TRAINING
  name: Corda Training Course

sections:
  - 01-blockchain
  - 02-corda
  - 03-run-example
  - 04-first-code
  - 05-libraries

assets:
  assetfolder: assets/images/
  external_asset_url: http://assetcdn.com/
  replace_git_folder: http://git.b9lab.com/client-projects/r3-corda-education-services/raw/master/
  section_asset_folders:
    - images
    - videos
  enable_crawl_git: true
  enable_crawl_section: true

preprocessor:

compiler:
  flatten_output: false
  create_anchors: false

export:
  export_mdx: true
  export_edx_html: true

output:
  fixed_output_folder: build
